/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this templa
    @Override
    public int getSize() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public E getElementAt(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
te file, choose Tools | Templates
 * and open the template in the editor.
 */
package bufetePackage;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;

/**
 *
 * @author draco
 */
public class BufeteJFrame extends javax.swing.JFrame {

    /**
     * Constructor de la clase
     */
    public BufeteJFrame() {
        gestion = new GestionBufete();
        listaClientes = new ArrayList<String[]>();
        clienteActual = new Cliente();
        tipoBusqueda = 0;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldBuscador = new javax.swing.JTextField();
        jLabelBuscador = new javax.swing.JLabel();
        jScrollPaneListaClientes = new javax.swing.JScrollPane();
        jListClientes = new javax.swing.JList();
        jComboBoxBuscador = new javax.swing.JComboBox();
        jTabbedPane1DatosCliente = new javax.swing.JTabbedPane();
        jPanelDatosPersonales = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabelIdentificador = new javax.swing.JLabel();
        jTextFieldIdentificador = new javax.swing.JTextField();
        jLabelDomicilio = new javax.swing.JLabel();
        jTextFieldDomicilio = new javax.swing.JTextField();
        jLabelAnotaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAnotacionesCliente = new javax.swing.JTextArea();
        jTextFieldLocalidad = new javax.swing.JTextField();
        jLabelTipoEntidad = new javax.swing.JLabel();
        jLabelLocalidad = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonActualizarDatos = new javax.swing.JButton();
        jCheckBoxJuridica = new javax.swing.JCheckBox();
        jPanelProcedimiento = new javax.swing.JPanel();
        jLabelProcedimiento = new javax.swing.JLabel();
        jComboBoxProcedimiento = new javax.swing.JComboBox();
        jLabelJuzgado = new javax.swing.JLabel();
        jTextFieldJuzgado = new javax.swing.JTextField();
        jLabelTipoProcedimiento = new javax.swing.JLabel();
        jTextFieldTipoProcedimiento = new javax.swing.JTextField();
        jLabelEstadoProcedimiento = new javax.swing.JLabel();
        jLabelMinuta = new javax.swing.JLabel();
        jTextFieldMinuta = new javax.swing.JTextField();
        jLabelPagado = new javax.swing.JLabel();
        jTextFieldPagado = new javax.swing.JTextField();
        jLabelNumeroProcedimiento = new javax.swing.JLabel();
        jTextFieldNumeroProcedimiento = new javax.swing.JTextField();
        jLabelAnotacionesProcedimiento = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAnotacionesProcedimiento = new javax.swing.JTextArea();
        jButtonActualizarProcedimiento = new javax.swing.JButton();
        jLabelFecha = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProcurador = new javax.swing.JTextField();
        jLabelProcuradorContrario = new javax.swing.JLabel();
        jLabelProcuradorContrario2 = new javax.swing.JLabel();
        jTextFieldProcuradorContrario = new javax.swing.JTextField();
        jCheckBoxAbierto = new javax.swing.JCheckBox();
        jLabelExpediente = new javax.swing.JLabel();
        jTextFieldExpediente = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jMenuBarMenus = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemAñadirCliente = new javax.swing.JMenuItem();
        jMenuItemAñadirProcedimiento = new javax.swing.JMenuItem();
        jMenuItemConectarUsuario = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuItemPreferencias = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTextFieldBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBuscadorKeyTyped(evt);
            }
        });

        jLabelBuscador.setText("Buscar por:");

        modeloListaClientes = new javax.swing.DefaultListModel();
        jListClientes.setModel(modeloListaClientes);
        jListClientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListClientesValueChanged(evt);
            }
        });
        jScrollPaneListaClientes.setViewportView(jListClientes);

        jComboBoxBuscador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre", "NIF", "Procedimiento", "Juzgado", "Expediente" }));
        jComboBoxBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBuscadorActionPerformed(evt);
            }
        });

        jLabelNombre.setText("Nombre");
        jLabelNombre.setToolTipText("Nombre del cliente");

        jLabelApellido1.setText("Apellidos");

        jLabelIdentificador.setText("NIF");

        jLabelDomicilio.setText("Domicilio");

        jLabelAnotaciones.setText("Anotaciones");

        jTextAreaAnotacionesCliente.setEditable(false);
        jTextAreaAnotacionesCliente.setColumns(20);
        jTextAreaAnotacionesCliente.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAnotacionesCliente);

        jLabelTipoEntidad.setText("Entidad");

        jLabelLocalidad.setText("Localidad");

        jLabelCodigo.setText("CP");

        jButtonActualizarDatos.setText("Actualizar");
        jButtonActualizarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonActualizarDatosMouseClicked(evt);
            }
        });

        jCheckBoxJuridica.setText("Jurídica");

        javax.swing.GroupLayout jPanelDatosPersonalesLayout = new javax.swing.GroupLayout(jPanelDatosPersonales);
        jPanelDatosPersonales.setLayout(jPanelDatosPersonalesLayout);
        jPanelDatosPersonalesLayout.setHorizontalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelIdentificador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelApellido1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                    .addComponent(jLabelAnotaciones)
                    .addComponent(jLabelLocalidad)
                    .addComponent(jButtonActualizarDatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addComponent(jTextFieldApellido2)
                    .addComponent(jTextFieldDomicilio)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(jTextFieldIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTipoEntidad)
                        .addGap(47, 47, 47)
                        .addComponent(jCheckBoxJuridica))
                    .addComponent(jTextFieldNombre)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(jTextFieldLocalidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosPersonalesLayout.setVerticalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido1)
                    .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIdentificador)
                    .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTipoEntidad)
                        .addComponent(jCheckBoxJuridica)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDomicilio)
                    .addComponent(jTextFieldDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLocalidad)
                    .addComponent(jLabelCodigo)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(jLabelAnotaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonActualizarDatos))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1DatosCliente.addTab("Datos Personales", jPanelDatosPersonales);

        jLabelProcedimiento.setText("Procedimiento");

        jComboBoxProcedimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProcedimientoActionPerformed(evt);
            }
        });

        jLabelJuzgado.setText("Juzgado");

        jLabelTipoProcedimiento.setText("Tipo");

        jLabelEstadoProcedimiento.setText("Estado");

        jLabelMinuta.setText("Minuta");

        jLabelPagado.setText("Pagado");

        jLabelNumeroProcedimiento.setText("Procedimiento");

        jLabelAnotacionesProcedimiento.setText("Anotaciones");

        jTextAreaAnotacionesProcedimiento.setColumns(20);
        jTextAreaAnotacionesProcedimiento.setRows(5);
        jScrollPane2.setViewportView(jTextAreaAnotacionesProcedimiento);

        jButtonActualizarProcedimiento.setText("Actualizar");
        jButtonActualizarProcedimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonActualizarProcedimientoMouseClicked(evt);
            }
        });

        jLabelFecha.setText("Fecha");

        jLabel1.setText("Procurador");

        jLabelProcuradorContrario.setText("Procurador");

        jLabelProcuradorContrario2.setText("Contrario");

        jCheckBoxAbierto.setText("Abierto");

        jLabelExpediente.setText("Expediente");

        jTextFieldExpediente.setEditable(false);

        javax.swing.GroupLayout jPanelProcedimientoLayout = new javax.swing.GroupLayout(jPanelProcedimiento);
        jPanelProcedimiento.setLayout(jPanelProcedimientoLayout);
        jPanelProcedimientoLayout.setHorizontalGroup(
            jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProcedimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelProcedimientoLayout.createSequentialGroup()
                            .addComponent(jLabelProcedimiento)
                            .addGap(63, 63, 63)
                            .addComponent(jComboBoxProcedimiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelProcedimientoLayout.createSequentialGroup()
                            .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelNumeroProcedimiento)
                                .addComponent(jLabelTipoProcedimiento))
                            .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelProcedimientoLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelEstadoProcedimiento)
                                    .addGap(27, 27, 27)
                                    .addComponent(jCheckBoxAbierto))
                                .addGroup(jPanelProcedimientoLayout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jTextFieldNumeroProcedimiento))))
                        .addGroup(jPanelProcedimientoLayout.createSequentialGroup()
                            .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelAnotacionesProcedimiento)
                                .addComponent(jLabelMinuta)
                                .addComponent(jLabel1)
                                .addComponent(jLabelProcuradorContrario)
                                .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonActualizarProcedimiento, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelExpediente)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                                .addComponent(jTextFieldProcurador)
                                .addComponent(jTextFieldProcuradorContrario)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProcedimientoLayout.createSequentialGroup()
                                    .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldTipoProcedimiento, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelProcedimientoLayout.createSequentialGroup()
                                            .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextFieldMinuta, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                                .addComponent(jTextFieldExpediente))
                                            .addGap(40, 40, 40)
                                            .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelPagado)
                                                .addComponent(jLabelFecha))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldPagado, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                        .addComponent(jTextFieldFecha)))))
                        .addGroup(jPanelProcedimientoLayout.createSequentialGroup()
                            .addComponent(jLabelJuzgado)
                            .addGap(54, 54, 54)
                            .addComponent(jTextFieldJuzgado)))
                    .addComponent(jLabelProcuradorContrario2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelProcedimientoLayout.setVerticalGroup(
            jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProcedimientoLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProcedimiento)
                    .addComponent(jComboBoxProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProcedimientoLayout.createSequentialGroup()
                        .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumeroProcedimiento)
                            .addComponent(jTextFieldNumeroProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabelJuzgado))
                    .addComponent(jTextFieldJuzgado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldTipoProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelEstadoProcedimiento)
                        .addComponent(jCheckBoxAbierto))
                    .addComponent(jLabelTipoProcedimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMinuta)
                    .addComponent(jTextFieldMinuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPagado)
                    .addComponent(jTextFieldPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelExpediente)
                    .addComponent(jTextFieldExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldProcurador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProcuradorContrario)
                    .addComponent(jTextFieldProcuradorContrario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabelProcuradorContrario2)
                .addGap(1, 1, 1)
                .addGroup(jPanelProcedimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProcedimientoLayout.createSequentialGroup()
                        .addComponent(jLabelAnotacionesProcedimiento)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonActualizarProcedimiento))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jTabbedPane1DatosCliente.addTab("Procedimiento", jPanelProcedimiento);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseClicked(evt);
            }
        });

        jMenuArchivo.setText("Archivo");

        jMenuItemAñadirCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAñadirCliente.setText("Añadir cliente");
        jMenuItemAñadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAñadirClienteActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemAñadirCliente);

        jMenuItemAñadirProcedimiento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAñadirProcedimiento.setText("Añadir procedimiento");
        jMenuItemAñadirProcedimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAñadirProcedimientoActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemAñadirProcedimiento);

        jMenuItemConectarUsuario.setText("Conectar Usuario");
        jMenuItemConectarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConectarUsuarioActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemConectarUsuario);

        jMenuBarMenus.add(jMenuArchivo);

        jMenuEditar.setText("Editar");

        jMenuItemPreferencias.setText("Preferencias");
        jMenuEditar.add(jMenuItemPreferencias);

        jMenuBarMenus.add(jMenuEditar);

        setJMenuBar(jMenuBarMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxBuscador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jButtonBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPaneListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1DatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBuscador)
                    .addComponent(jComboBoxBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneListaClientes)
                    .addComponent(jTabbedPane1DatosCliente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cambia el tipo de búsqueda al seleccionado en jComboBoxBuscador
     * 
     * @param evt 
     */
    private void jComboBoxBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBuscadorActionPerformed
        tipoBusqueda = jComboBoxBuscador.getSelectedIndex();
    }//GEN-LAST:event_jComboBoxBuscadorActionPerformed
    /**
     * Cierra la conexión con la base de datos y finaliza el programa
     * 
     * @param evt 
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            if (con != null)
                con.close();
        } catch (SQLException ex) {
            Logger lgr = Logger.getLogger(BufeteJFrame.class.getName());
            lgr.log(Level.SEVERE, ex.getMessage(), ex);
        }
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing
    /**
     * Realiza una búsqueda cuando se pulsa ENTER en el buscador
     * @param evt 
     */
    private void jTextFieldBuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscadorKeyTyped
        if ((evt.getKeyChar() == '\n') && gestion.isConnected()){
            listaClientes = gestion.busqueda(tipoBusqueda, jTextFieldBuscador.getText());
            modeloListaClientes.clear();   
            if (listaClientes != null){
                int contador = 0;
                while (contador < listaClientes.size() ){
                    modeloListaClientes.addElement(listaClientes.get(contador)[0]);
                    contador++;
                }
            }
        }
    }//GEN-LAST:event_jTextFieldBuscadorKeyTyped
    /**
     * Realiza una búsqueda al hacer clic en el botón de búsqueda
     * 
     * @param evt 
     */
    private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseClicked
        if (gestion.isConnected()) {
            listaClientes = gestion.busqueda(tipoBusqueda, jTextFieldBuscador.getText());
            modeloListaClientes.clear();        
            if (listaClientes != null){
                int contador = 0;
                while (contador < listaClientes.size() ){
                    modeloListaClientes.addElement(listaClientes.get(contador)[0]);
                    contador++;
                }
            }
        }
    }//GEN-LAST:event_jButtonBuscarMouseClicked
    /**
     * Si cambia el cliente seleccionado de la lista de clientes, realiza la
     * búsqueda de los datos y el primer procedimiento del mismo
     * @param evt 
     */
    private void jListClientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListClientesValueChanged
        if ((evt.getValueIsAdjusting() == false) && gestion.isConnected()){
            String identificador = new String();
            identificador = listaClientes.get(jListClientes.getSelectedIndex())[1];
            clienteActual = gestion.busquedaDatos(identificador);
            if (clienteActual.getNombre() != null)
                jTextFieldNombre.setText(clienteActual.getNombre());
            else
                jTextFieldNombre.setText("");
            if (clienteActual.getApellido1() != null)
                jTextFieldApellido1.setText(clienteActual.getApellido1());
            else
                jTextFieldApellido1.setText("");
            if (clienteActual.getApellido2() != null)
                jTextFieldApellido2.setText(clienteActual.getApellido2());
            else
                jTextFieldApellido2.setText("");
            if (clienteActual.isJuridica()){
                if (!jCheckBoxJuridica.isSelected())
                    jCheckBoxJuridica.doClick();
            }
            else{
                if (jCheckBoxJuridica.isSelected())
                    jCheckBoxJuridica.doClick();
            }   
            jTextFieldIdentificador.setText(clienteActual.getIdentificador().toString());
            if (clienteActual.getDomicilio() != null) {
                jTextFieldDomicilio.setText(clienteActual.getDomicilio().toString());
                jTextFieldLocalidad.setText(clienteActual.getDomicilio().getLocalidad());
                        //+ "(" + clienteActual.getDomicilio().getProvincia() + ")"); TODO
                jTextFieldCodigo.setText(Integer.toString(clienteActual.getDomicilio().getCodigo()));
            } else {
                jTextFieldDomicilio.setText("");
                jTextFieldLocalidad.setText("");
                jTextFieldCodigo.setText("");
            }
            if (clienteActual.getAnotaciones() != null)
                jTextAreaAnotacionesCliente.setText(clienteActual.getAnotaciones());
            else
                jTextAreaAnotacionesCliente.setText("");
            // Primer procedimiento
            if (clienteActual.getListaProcedimientos() != null){
                int contador = 0;
                while (contador < clienteActual.getListaProcedimientos().size()) {
                    jComboBoxProcedimiento.addItem(clienteActual.getProcedimiento(contador).getNig());
                    contador++;
                }
                jTextFieldNumeroProcedimiento.setText(clienteActual.getProcedimiento(0).getNig());
                jTextFieldJuzgado.setText(clienteActual.getProcedimiento(0).getJuzgado());
                jTextFieldTipoProcedimiento.setText(clienteActual.getProcedimiento(0).getTipoDeProcedimiento());
                if (clienteActual.getProcedimiento(0).isAbierto()){
                    if (!jCheckBoxAbierto.isSelected())
                        jCheckBoxAbierto.doClick();
                } else {
                    if (jCheckBoxAbierto.isSelected())
                        jCheckBoxAbierto.doClick();
                }
                jTextFieldMinuta.setText("" + clienteActual.getProcedimiento(0).getMinuta() + "€");
                jTextFieldPagado.setText("" + clienteActual.getProcedimiento(0).getPagado() + "€");
                jTextAreaAnotacionesProcedimiento.setText(clienteActual.getProcedimiento(0).getAnotaciones());
            } else {
                jComboBoxProcedimiento.removeAllItems();
                jTextFieldNumeroProcedimiento.setText("");
                jTextFieldJuzgado.setText("");
                jTextFieldTipoProcedimiento.setText("");
                if (jCheckBoxAbierto.isSelected())
                    jCheckBoxAbierto.doClick();
                jTextFieldMinuta.setText("");
                jTextFieldPagado.setText("");
                jTextAreaAnotacionesProcedimiento.setText("");
            }
        }
    }//GEN-LAST:event_jListClientesValueChanged
    /**
     * Busca los datos del procedimiento seleccionado
     * 
     * @param evt 
     */
    private void jComboBoxProcedimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProcedimientoActionPerformed
        if (clienteActual.getListaProcedimientos() != null){
            jTextFieldNumeroProcedimiento.setText(""
                    + clienteActual.getProcedimiento(jComboBoxProcedimiento.getSelectedIndex()).getNig());
            jTextFieldJuzgado.setText(""
                    + clienteActual.getProcedimiento(jComboBoxProcedimiento.getSelectedIndex()).getJuzgado());
            jTextFieldTipoProcedimiento.setText(""
                    + clienteActual.getProcedimiento(jComboBoxProcedimiento.getSelectedIndex()).getTipoDeProcedimiento());
            if (clienteActual.getProcedimiento(jComboBoxProcedimiento.getSelectedIndex()).isAbierto()){
                if (!jCheckBoxAbierto.isSelected())
                    jCheckBoxAbierto.doClick();
            } else {
                if (jCheckBoxAbierto.isSelected())
                    jCheckBoxAbierto.doClick();
            }
            jTextFieldMinuta.setText(""
                    + clienteActual.getProcedimiento(jComboBoxProcedimiento.getSelectedIndex()).getMinuta() + "€");
            jTextFieldPagado.setText(""
                    + clienteActual.getProcedimiento(jComboBoxProcedimiento.getSelectedIndex()).getPagado() + "€");
            jTextFieldExpediente.setText(""
                    + clienteActual.getProcedimiento(jComboBoxProcedimiento.getSelectedIndex()).getExpediente());
            jTextFieldFecha.setText(""
                    + clienteActual.getProcedimiento(jComboBoxProcedimiento.getSelectedIndex()).getFecha());
            jTextAreaAnotacionesProcedimiento.setText(""
                    + clienteActual.getProcedimiento(jComboBoxProcedimiento.getSelectedIndex()).getAnotaciones());
        }
    }//GEN-LAST:event_jComboBoxProcedimientoActionPerformed
    /**
     * Actualiza los datos del cliente al hacer clic en el botón
     * 
     * @param evt 
     */
    private void jButtonActualizarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonActualizarDatosMouseClicked
        if (gestion.isConnected()) {
            String nombre = jTextFieldNombre.getText();
            String apellido1 = jTextFieldApellido1.getText();
            String apellido2 = jTextFieldApellido2.getText();
            String nif = jTextFieldIdentificador.getText();
            boolean juridica = jCheckBoxJuridica.isSelected();
            String domicilio = jTextFieldDomicilio.getText();
            String localidad = jTextFieldLocalidad.getText();
            String codigo = jTextFieldCodigo.getText();
            gestion.updateCliente(nombre, apellido1, apellido2, nif, juridica, domicilio, localidad, codigo, nif);
        }
    }//GEN-LAST:event_jButtonActualizarDatosMouseClicked
    /**
     * Actualiza los datos del procedimiento al hacer clic en el botón
     * 
     * @param evt 
     */
    private void jButtonActualizarProcedimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonActualizarProcedimientoMouseClicked
        if (gestion.isConnected()) {
            String numero = jTextFieldNumeroProcedimiento.getText();
            String juzgado = jTextFieldJuzgado.getText();
            String tipoProcedimiento = jTextFieldTipoProcedimiento.getText();
            boolean abierto = jCheckBoxAbierto.isSelected();
            String minutaString = jTextFieldMinuta.getText();
            minutaString = minutaString.substring(0,minutaString.length()-1);
            float minuta = Float.parseFloat(minutaString);
            String pagadoString = jTextFieldPagado.getText();
            pagadoString = pagadoString.substring(0,pagadoString.length()-1);
            float pagado = Float.parseFloat(pagadoString);
            String fecha = jTextFieldFecha.getText();
            String procurador = jTextFieldProcurador.getText();
            String procuradorContrario = jTextFieldProcuradorContrario.getText();
            String anotaciones = jTextAreaAnotacionesProcedimiento.getText();
        
            gestion.updateProcedimiento(numero, juzgado, tipoProcedimiento, abierto, minuta,
                    pagado, fecha, procurador, procuradorContrario, anotaciones);
        }
    }//GEN-LAST:event_jButtonActualizarProcedimientoMouseClicked
    /**
     * Crea una ventana para introducir los datos del usuario y conectarse
     * 
     * @param evt 
     */
    private void jMenuItemConectarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConectarUsuarioActionPerformed
        Conectar conexion = new Conectar(gestion, "Conectar Usuario");
        conexion.setVisible(true);
    }//GEN-LAST:event_jMenuItemConectarUsuarioActionPerformed
    /**
     * Crea un formulario para añadir un nuevo cliente
     * 
     * @param evt 
     */
    private void jMenuItemAñadirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAñadirClienteActionPerformed
        FormularioCliente formulario = new FormularioCliente(gestion, "Nuevo cliente");
        formulario.setVisible(true);
    }//GEN-LAST:event_jMenuItemAñadirClienteActionPerformed
    /**
     * Crea un formulario para añadir un nuevo procedimiento
     * @param evt 
     */
    private void jMenuItemAñadirProcedimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAñadirProcedimientoActionPerformed
        FormularioProcedimiento formulario = new FormularioProcedimiento(gestion, "Nuevo procedimiento");
        formulario.setVisible(true);
    }//GEN-LAST:event_jMenuItemAñadirProcedimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BufeteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BufeteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BufeteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BufeteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BufeteJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizarDatos;
    private javax.swing.JButton jButtonActualizarProcedimiento;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JCheckBox jCheckBoxAbierto;
    private javax.swing.JCheckBox jCheckBoxJuridica;
    private javax.swing.JComboBox jComboBoxBuscador;
    private javax.swing.JComboBox jComboBoxProcedimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAnotaciones;
    private javax.swing.JLabel jLabelAnotacionesProcedimiento;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelBuscador;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDomicilio;
    private javax.swing.JLabel jLabelEstadoProcedimiento;
    private javax.swing.JLabel jLabelExpediente;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelIdentificador;
    private javax.swing.JLabel jLabelJuzgado;
    private javax.swing.JLabel jLabelLocalidad;
    private javax.swing.JLabel jLabelMinuta;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumeroProcedimiento;
    private javax.swing.JLabel jLabelPagado;
    private javax.swing.JLabel jLabelProcedimiento;
    private javax.swing.JLabel jLabelProcuradorContrario;
    private javax.swing.JLabel jLabelProcuradorContrario2;
    private javax.swing.JLabel jLabelTipoEntidad;
    private javax.swing.JLabel jLabelTipoProcedimiento;
    private javax.swing.JList jListClientes;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBarMenus;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuItemAñadirCliente;
    private javax.swing.JMenuItem jMenuItemAñadirProcedimiento;
    private javax.swing.JMenuItem jMenuItemConectarUsuario;
    private javax.swing.JMenuItem jMenuItemPreferencias;
    private javax.swing.JPanel jPanelDatosPersonales;
    private javax.swing.JPanel jPanelProcedimiento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneListaClientes;
    private javax.swing.JTabbedPane jTabbedPane1DatosCliente;
    private javax.swing.JTextArea jTextAreaAnotacionesCliente;
    private javax.swing.JTextArea jTextAreaAnotacionesProcedimiento;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldBuscador;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDomicilio;
    private javax.swing.JTextField jTextFieldExpediente;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldIdentificador;
    private javax.swing.JTextField jTextFieldJuzgado;
    private javax.swing.JTextField jTextFieldLocalidad;
    private javax.swing.JTextField jTextFieldMinuta;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroProcedimiento;
    private javax.swing.JTextField jTextFieldPagado;
    private javax.swing.JTextField jTextFieldProcurador;
    private javax.swing.JTextField jTextFieldProcuradorContrario;
    private javax.swing.JTextField jTextFieldTipoProcedimiento;
    // End of variables declaration//GEN-END:variables
    
    private javax.swing.DefaultListModel modeloListaClientes;
    private static Connection con;
    private static final String url = "jdbc:mysql://localhost:3306/bufete";
    private static GestionBufete gestion;
    private int tipoBusqueda;
    private ArrayList<String[]> listaClientes;
    private Cliente clienteActual;
    
}
