/*
 * Copyright (C) 2015 draco
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package bufetePackage;

import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author draco
 */
public class FormularioProcedimiento extends javax.swing.JFrame {

    /**
     * Creates new form FormularioProcedimiento
     */
    public FormularioProcedimiento(GestionBufete gestion, String cabecera) {
        super(cabecera);
        this.gestion = gestion;
        initComponents();
    }

    public boolean isAbierto() {
        return jCheckBoxAbierto.isSelected();
    }

    public String getDNICliente() {
        return jTextFieldDNICliente.getText();
    }

    public String getFecha() {
        String fecha = jTextFieldYear.getText()+"-"+jTextFieldMes.getText()+"-"+jTextFieldDia.getText();
                return fecha;
    }

    public String getJuzgado() {
        return jTextFieldJuzgado.getText();
    }

    public String getMinuta() {
        return jTextFieldMinuta.getText();
    }

    public String getNumeroProcedimiento() {
        return jTextFieldNumeroProcedimiento.getText();
    }

    public String getPagado() {
        return jTextFieldPagado.getText();
    }

    public String getProcurador() {
        return jTextFieldProcurador.getText();
    }

    public String getProcuradorContrario() {
        return jTextFieldProcuradorContrario.getText();
    }

    public String getTipoProcedimiento() {
        return jTextFieldTipoProcedimiento.getText();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNumeroProcedimiento = new javax.swing.JTextField();
        jTextFieldJuzgado = new javax.swing.JTextField();
        jTextFieldTipoProcedimiento = new javax.swing.JTextField();
        jTextFieldMinuta = new javax.swing.JTextField();
        jLabelNumeroProcedimiento = new javax.swing.JLabel();
        jLabelJuzgado = new javax.swing.JLabel();
        jLabelTipoProcedimiento = new javax.swing.JLabel();
        jLabelMinuta = new javax.swing.JLabel();
        jLabelEstadoProcediminto = new javax.swing.JLabel();
        jCheckBoxAbierto = new javax.swing.JCheckBox();
        jLabelPagado = new javax.swing.JLabel();
        jTextFieldPagado = new javax.swing.JTextField();
        jLabelFecha = new javax.swing.JLabel();
        jTextFieldDia = new javax.swing.JTextField();
        jLabelProcurador = new javax.swing.JLabel();
        jTextFieldProcurador = new javax.swing.JTextField();
        jLabelProcuradorContrario1 = new javax.swing.JLabel();
        jLabelProcuradorContrario2 = new javax.swing.JLabel();
        jLabelDNICliente = new javax.swing.JLabel();
        jTextFieldDNICliente = new javax.swing.JTextField();
        jTextFieldProcuradorContrario = new javax.swing.JTextField();
        jButtonAddProcedimiento = new javax.swing.JButton();
        jLabelDia = new javax.swing.JLabel();
        jLabelMes = new javax.swing.JLabel();
        jTextFieldMes = new javax.swing.JTextField();
        jLabelYear = new javax.swing.JLabel();
        jTextFieldYear = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNumeroProcedimiento.setText("Nº Procedimiento");

        jLabelJuzgado.setText("Juzgado");

        jLabelTipoProcedimiento.setText("Tipo");

        jLabelMinuta.setText("Minuta");

        jLabelEstadoProcediminto.setText("Estado");

        jCheckBoxAbierto.setText("Abierto");

        jLabelPagado.setText("Pagado");

        jLabelFecha.setText("Fecha");

        jLabelProcurador.setText("Procurador");

        jLabelProcuradorContrario1.setText("Procurador");

        jLabelProcuradorContrario2.setText("Contrario");

        jLabelDNICliente.setText("DNI Cliente");

        jButtonAddProcedimiento.setText("Añadir procedimiento");
        jButtonAddProcedimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProcedimientoActionPerformed(evt);
            }
        });

        jLabelDia.setText("Día");

        jLabelMes.setText("Mes");

        jLabelYear.setText("Año");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumeroProcedimiento)
                    .addComponent(jLabelTipoProcedimiento)
                    .addComponent(jLabelProcurador)
                    .addComponent(jLabelProcuradorContrario1)
                    .addComponent(jLabelDNICliente)
                    .addComponent(jLabelProcuradorContrario2)
                    .addComponent(jLabelJuzgado)
                    .addComponent(jLabelMinuta)
                    .addComponent(jLabelFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldTipoProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelEstadoProcediminto)
                        .addGap(43, 43, 43)
                        .addComponent(jCheckBoxAbierto))
                    .addComponent(jTextFieldJuzgado)
                    .addComponent(jTextFieldProcurador)
                    .addComponent(jTextFieldProcuradorContrario)
                    .addComponent(jTextFieldNumeroProcedimiento)
                    .addComponent(jTextFieldDNICliente)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabelPagado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jTextFieldMinuta, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabelYear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAddProcedimiento)
                .addGap(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDNICliente)
                    .addComponent(jTextFieldDNICliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroProcedimiento)
                    .addComponent(jTextFieldNumeroProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldJuzgado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJuzgado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstadoProcediminto)
                    .addComponent(jCheckBoxAbierto)
                    .addComponent(jLabelTipoProcedimiento)
                    .addComponent(jTextFieldTipoProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPagado)
                            .addComponent(jTextFieldMinuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDia))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMinuta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFecha)
                            .addComponent(jTextFieldDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMes)
                            .addComponent(jTextFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelYear)
                            .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProcurador)
                    .addComponent(jTextFieldProcurador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProcuradorContrario1)
                    .addComponent(jTextFieldProcuradorContrario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProcuradorContrario2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddProcedimiento)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddProcedimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProcedimientoActionPerformed
        // TODO add your handling code here:
        gestion.addProcedimiento(this.getDNICliente(), this.getNumeroProcedimiento(), this.getJuzgado(),
                this.getTipoProcedimiento(), this.isAbierto(), Float.parseFloat(this.getMinuta()),
                Float.parseFloat(this.getPagado()), this.getFecha(), this.getProcurador(), 
                this.getProcuradorContrario());
        this.dispose();
    }//GEN-LAST:event_jButtonAddProcedimientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddProcedimiento;
    private javax.swing.JCheckBox jCheckBoxAbierto;
    private javax.swing.JLabel jLabelDNICliente;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelEstadoProcediminto;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelJuzgado;
    private javax.swing.JLabel jLabelMes;
    private javax.swing.JLabel jLabelMinuta;
    private javax.swing.JLabel jLabelNumeroProcedimiento;
    private javax.swing.JLabel jLabelPagado;
    private javax.swing.JLabel jLabelProcurador;
    private javax.swing.JLabel jLabelProcuradorContrario1;
    private javax.swing.JLabel jLabelProcuradorContrario2;
    private javax.swing.JLabel jLabelTipoProcedimiento;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JTextField jTextFieldDNICliente;
    private javax.swing.JTextField jTextFieldDia;
    private javax.swing.JTextField jTextFieldJuzgado;
    private javax.swing.JTextField jTextFieldMes;
    private javax.swing.JTextField jTextFieldMinuta;
    private javax.swing.JTextField jTextFieldNumeroProcedimiento;
    private javax.swing.JTextField jTextFieldPagado;
    private javax.swing.JTextField jTextFieldProcurador;
    private javax.swing.JTextField jTextFieldProcuradorContrario;
    private javax.swing.JTextField jTextFieldTipoProcedimiento;
    private javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables
    private GestionBufete gestion;
}
